name: Release

on:
  push:
    tags:
      - "v*"
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch: # 允许手动触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 需要获取所有历史来生成完整的变更日志

      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        id: draft_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 只有在推送标签时才创建正式发布
      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.draft_release.outputs.body }}
          files: |
            dist/*.dll
            dist/*.me
            dist/*.rar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    